services:
  - type: web
    name: one-v-one-render-static
    runtime: static
    buildCommand: node build-static-site.js
    staticPublishPath: ./static-dist
    envVars:
      - key: WS_BRIDGE_BASE_URL
        value: wss://one-v-one-render-bridge.onrender.com
      - key: NODE_VERSION
        value: "20"
  - type: web
    name: one-v-one-render-bridge
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm install --omit=dev
    startCommand: npm start
    healthCheckPath: /healthz
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: WS_TARGET_FRANKFURT
        value: ""
